# Generated by Django 5.0.3 on 2024-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOldChicksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=300)),
                ('layers', models.BooleanField()),
                ('broilers', models.BooleanField()),
                ('kenbros', models.BooleanField()),
                ('numberOfBirds', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
