# Generated by Django 5.0.3 on 2024-03-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=60)),
                ('CheckoutRequestID', models.CharField(max_length=60)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.CharField(max_length=150)),
                ('Amount', models.FloatField()),
                ('MpesaReceiptNumber', models.CharField(max_length=20)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lnm_payments', to='products.order')),
            ],
        ),
    ]
