# Generated by Django 5.0.3 on 2024-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('drugs', 'Drugs'), ('feeding_brooders', 'Feeding Brooders'), ('feeds', 'Feeds'), ('labour', 'Labour'), ('maintenance_costs', 'Maintenance Costs'), ('equipment', 'Poultry Farm Equipment'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('establishment_date', models.DateField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['establishment_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('eggs', 'Eggs'), ('chickens', 'Chickens'), ('manure', 'Manure'), ('other', 'Other Poultry Products')], max_length=20)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('amount_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_in_weeks', models.PositiveIntegerField()),
                ('no_of_poultries', models.PositiveIntegerField()),
                ('breed', models.CharField(choices=[('Kenbro', 'Kenbro'), ('Broiler', 'Broiler'), ('Layers', 'Layers')], max_length=50)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('description', models.TextField(default=True)),
            ],
            options={
                'ordering': ['date_add'],
            },
        ),
    ]
