# Generated by Django 5.0.3 on 2024-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_expense_date_alter_farm_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(default='poultries farming'),
            preserve_default=False,
        ),
    ]
