# Generated by Django 5.0.3 on 2024-03-23 01:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_farm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
