# Generated by Django 5.0.3 on 2024-03-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_farm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
    ]
