# Generated by Django 5.0.3 on 2024-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_farm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(),
        ),
    ]
