# Generated by Django 5.0.3 on 2024-03-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
